const publication = [
        {
        id:1,
        publicationName:"Телепрограмма на 31 декабря 2016 года",
        limitationAge:"0+",
        image:"img/publication_img4.jpg",
        text:"Новогодняя ночь (с 31 декабря 2016 года на 1 января 2017 года) уже скоро и уже всех интересует вопрос, что для нас подготовили в новогодней программе по телевиденью.",
        linkItem:"/1",
        date:"21/12/2016",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:2,
        publicationName:"КАК НА САМОМ ДЕЛЕ СНИМАЮТЬСЯ ФИЛЬМЫ",
        limitationAge:"0+",
        image:"img/publication_img1.jpg",
        text:"Готова поспорить, что многие даже не подозревают как часто постановщики используют компьютерную графику при создании фильма и в каких местах фильма.",
        // linkItem,
        date:"28/01/2017",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:3,
        publicationName:"Модные луки из сериала «В стиле Джейн» (Jane by Design)",
        limitationAge:"12+",
        image:"img/publication_img2.jpg",
        text:"Наверно многие замечали, что влияние на модные тенденции берет свои корни из того что нам показывают по телевизору и в кино. К одним из таких кладезей модных образов можно отнести сериал «В стиле Джейн» (Jane by Design) 2012 года.",
        // linkItem,
        date:"28/01/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:4,
        publicationName:"Процесс превращения в Гамору (Стражи Галактики)",
        limitationAge:"16+",
        image:"img/publication_img3.jpg",
        text:"Пока до премьеры фильма «Стражи Галактики 2» остаются считанные дни, премьера в России состоится 4 мая 2017 года, главная героиня фильма Зои Солдана продемонстрировала процесс превращения в Гамору.",
        // linkItem,
        date:"01/11/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:5,
        publicationName:"Телепрограмма на 31 декабря 2016 года",
        limitationAge:"0+",
        image:"img/publication_img4.jpg",
        text:"Новогодняя ночь (с 31 декабря 2016 года на 1 января 2017 года) уже скоро и уже всех интересует вопрос, что для нас подготовили в новогодней программе по телевиденью.",
        // linkItem,
        date:"21/12/2016",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:6,
        publicationName:"КАК НА САМОМ ДЕЛЕ СНИМАЮТЬСЯ ФИЛЬМЫ",
        limitationAge:"0+",
        image:"img/publication_img1.jpg",
        text:"Готова поспорить, что многие даже не подозревают как часто постановщики используют компьютерную графику при создании фильма и в каких местах фильма.",
        // linkItem,
        date:"28/01/2017",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:7,
        publicationName:"Модные луки из сериала «В стиле Джейн» (Jane by Design)",
        limitationAge:"12+",
        image:"img/publication_img2.jpg",
        text:"Наверно многие замечали, что влияние на модные тенденции берет свои корни из того что нам показывают по телевизору и в кино. К одним из таких кладезей модных образов можно отнести сериал «В стиле Джейн» (Jane by Design) 2012 года.",
        // linkItem,
        date:"28/01/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:8,
        publicationName:"Процесс превращения в Гамору (Стражи Галактики)",
        limitationAge:"16+",
        image:"img/publication_img3.jpg",
        text:"Пока до премьеры фильма «Стражи Галактики 2» остаются считанные дни, премьера в России состоится 4 мая 2017 года, главная героиня фильма Зои Солдана продемонстрировала процесс превращения в Гамору.",
        // linkItem,
        date:"01/11/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:9,
        publicationName:"Телепрограмма на 31 декабря 2016 года",
        limitationAge:"0+",
        image:"img/publication_img4.jpg",
        text:"Новогодняя ночь (с 31 декабря 2016 года на 1 января 2017 года) уже скоро и уже всех интересует вопрос, что для нас подготовили в новогодней программе по телевиденью.",
        // linkItem,
        date:"21/12/2016",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:10,
        publicationName:"КАК НА САМОМ ДЕЛЕ СНИМАЮТЬСЯ ФИЛЬМЫ",
        limitationAge:"0+",
        image:"img/publication_img1.jpg",
        text:"Готова поспорить, что многие даже не подозревают как часто постановщики используют компьютерную графику при создании фильма и в каких местах фильма.",
        // linkItem,
        date:"28/01/2017",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:11,
        publicationName:"Модные луки из сериала «В стиле Джейн» (Jane by Design)",
        limitationAge:"12+",
        image:"img/publication_img2.jpg",
        text:"Наверно многие замечали, что влияние на модные тенденции берет свои корни из того что нам показывают по телевизору и в кино. К одним из таких кладезей модных образов можно отнести сериал «В стиле Джейн» (Jane by Design) 2012 года.",
        // linkItem,
        date:"28/01/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:12,
        publicationName:"Процесс превращения в Гамору (Стражи Галактики)",
        limitationAge:"16+",
        image:"img/publication_img3.jpg",
        text:"Пока до премьеры фильма «Стражи Галактики 2» остаются считанные дни, премьера в России состоится 4 мая 2017 года, главная героиня фильма Зои Солдана продемонстрировала процесс превращения в Гамору.",
        // linkItem,
        date:"01/11/2018",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:13,
        publicationName:"Телепрограмма на 31 декабря 2016 года",
        limitationAge:"0+",
        image:"img/publication_img4.jpg",
        text:"Новогодняя ночь (с 31 декабря 2016 года на 1 января 2017 года) уже скоро и уже всех интересует вопрос, что для нас подготовили в новогодней программе по телевиденью.",
        // linkItem,
        date:"21/12/2016",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    {
        id:14,
        publicationName:"КАК НА САМОМ ДЕЛЕ СНИМАЮТЬСЯ ФИЛЬМЫ",
        limitationAge:"0+",
        image:"img/publication_img1.jpg",
        text:"Готова поспорить, что многие даже не подозревают как часто постановщики используют компьютерную графику при создании фильма и в каких местах фильма.",
        // linkItem,
        date:"28/01/2017",
        autorName:"dana",
        // linkItemComment,
        // linkMenu,
        // linkYearFilm
    },
    
]

export default publication;